name: "Tauri build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}

    permissions:
      contents: write  # 添加此行，授予写入权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install frontend dependencies
        run: pnpm install

      - name: Download FFmpeg (macOS)
        if: matrix.platform == 'macos-latest'
        shell: bash
        run: |
          FFMPEG_URL="https://evermeet.cx/ffmpeg/getrelease/ffmpeg/zip"
          download_path="src-tauri/resources/ffmpeg/ffmpeg.zip"
          install_dir="src-tauri/resources/ffmpeg"
          
          mkdir -p $install_dir
          curl -L $FFMPEG_URL -o $download_path
          unzip $download_path -d $install_dir

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}