name: "Tauri build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 Rust 和 Tauri CLI
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Tauri CLI
        run: cargo install tauri-cli

      # 在不同平台下载 FFmpeg
      - name: Download FFmpeg (Windows)
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          $ffmpegUrl = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
          $downloadPath = "resources/ffmpeg.zip"
          $installDir = "resources/ffmpeg"

          mkdir -p $installDir
          Invoke-WebRequest -Uri $ffmpegUrl -OutFile $downloadPath
          Expand-Archive -Path $downloadPath -DestinationPath $installDir
          # 将 ffmpeg.exe 移动到 resources/ffmpeg 根目录，以符合 Tauri 打包配置
          mv "${installDir}/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe" "${installDir}/ffmpeg.exe"

      - name: Download FFmpeg (macOS)
        if: matrix.platform == 'macos-latest'
        shell: bash
        run: |
          FFMPEG_URL="https://evermeet.cx/ffmpeg/getrelease/ffmpeg/zip"
          download_path="resources/ffmpeg.zip"
          install_dir="resources/ffmpeg"

          mkdir -p $install_dir
          curl -L $FFMPEG_URL -o $download_path
          unzip $download_path -d $install_dir
          # 将 ffmpeg 可执行文件移动到 resources/ffmpeg 根目录
          mv "${install_dir}/ffmpeg" "${install_dir}/ffmpeg-mac"

      - name: Download FFmpeg (Linux)
        if: matrix.platform == 'ubuntu-latest'
        shell: bash
        run: |
          FFMPEG_URL="https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz"
          download_path="resources/ffmpeg.tar.xz"
          install_dir="resources/ffmpeg"

          mkdir -p $install_dir
          curl -L $FFMPEG_URL -o $download_path
          tar -xf $download_path -C $install_dir --strip-components=1
          # 将 ffmpeg 可执行文件移动到 resources/ffmpeg 根目录
          mv "${install_dir}/ffmpeg" "${install_dir}/ffmpeg-linux"

      # 构建 Tauri 应用
      - name: Build Tauri app
        uses: tauri-apps/tauri-action@dev
        with:
          release: true
          # 你可以在这里传入其他参数，比如签名证书等